apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: taskmanager
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5000
  type: LoadBalancer